package:
  name: methlevels
  version: "v1"

source:
  path: ../

requirements:
  build:
  - python>=3.6
  - setuptools

  run:
    - dpcontracts=0.4.0
    - pandas>=0.23.4
    - joblib>=0.12
    - matplotlib>=3.0.0
    - seaborn>=0.9.0
    - numpy
    - pyranges
    - bedtools
    - htslib

  # optional dependencies
  # --------------------------------------------------------------------------------------
  # as of now (conda 4.5) there is nothing similar to extras_require in setuptools afaik
  # therefore, when installing via conda, all optional dependencies are also installed.
  # marking them in this extra section for when conda has more ways to deal with it
  # note that the run_constrained feature is not what we need here afaik

  # development dependencies
  - mypy
  - pytest

test:
  imports:
  - mqc

about:
  home: 'http://github.com/sjkv/mqc'
